import time
import shutil
import os
import platform
from typing import List, Tuple

class CreditsScroller:
    def __init__(self, scroll_speed: float = 0.290):
        """
        Initialize the credits scroller with configurable parameters.
        
        Args:
            scroll_speed: Time in seconds between each frame (lower = faster)
        """
        self.scroll_speed = scroll_speed
        self.terminal_width, self.terminal_height = self._get_terminal_size()
        self.credits = [
            "A Sarah Clark Production",
            "",
            "THE MIDNIGHT GARDEN",
            "",
            "Written and Directed by",
            "Sarah Clark",
            "",
            "Executive Producers:",
            "Mr. Light Pulse",
            "Alexandra Blackwood",
            "James Sterling III",
            "",
            "Starring",
            "Emma Sullivan as 'Clara'",
            "James O'Connell as 'Thomas'",
            "Victoria Adler as 'Eleanor'",
            "Marcus Renner as 'Dr. Phillips'",
            "Clara Fitzgerald as 'Young Clara'",
            "Oliver Hughes as 'The Gardener'",
            "Sophia Patel as 'Marie'",
            "Ethan Rivera as 'Detective Brooks'",
            "Lucas Thornton as 'The Stranger'",
            "Amelia Grayson as 'Sarah'",
            "Jessica Hall as 'Rebecca'",
            "Liam Peterson as 'David'",
            "Hannah Dawson as 'Elizabeth'",
            "Connor Dawson as 'James'",
            "Sebastian Knight as 'The Timekeeper'",
            "Victoria Clarke as 'Mrs. Hammond'",
            "William Brooks as 'Mr. Hammond'",
            "",
            "Supporting Cast",
            "Zara Chen as 'The Librarian'",
            "Rafael Martinez as 'Officer Rodriguez'",
            "Nina Patel as 'Dr. Kumar'",
            "Theodore Wells as 'The Shopkeeper'",
            "Isabella Romano as 'Young Eleanor'",
            "Felix Thompson as 'The Postal Worker'",
            "Diana Chang as 'The Neighbor'",
            "Marcus Webb as 'The Journalist'",
            "",
            "Stunts Coordinator:",
            "Katherine 'Kat' Rodriguez",
            "",
            "Stunt Team:",
            "Michael Chen",
            "Sarah Thompson",
            "David O'Brien",
            "Laura Martinez",
            "James Wilson",
            "Nina Rodriguez",
            "Keith Parker",
            "Maria Gonzalez",
            "",
            "Second Unit Director:",
            "Benjamin Foster",
            "",
            "Second Unit Photography:",
            "Rachel Montgomery",
            "Samuel Kim",
            "Elena Santos",
            "",
            "Production Design Team:",
            "Daniel Carmichael",
            "Tobias Grant",
            "Aria Blackwood",
            "Mason Chen",
            "Sophie Laurent",
            "Pedro Alvarez",
            "",
            "Art Department:",
            "Luna Martinez",
            "Xavier Thompson",
            "Yuki Tanaka",
            "Zoe Anderson",
            "Ahmed Hassan",
            "Blake Morrison",
            "",
            "Set Decoration:",
            "Penelope Miller",
            "Hannah Dawson",
            "William Brooks",
            "Iris Chen",
            "Marco Rossi",
            "Nina Patel",
            "",
            "Costume Design:",
            "Isabella Wright",
            "Grace Turner",
            "Liam O'Connor",
            "Sofia Rodriguez",
            "Theo Parker",
            "",
            "Makeup Department Head:",
            "Victoria Knight",
            "",
            "Key Makeup Artists:",
            "Ruby Chen",
            "Marco Baptiste",
            "Sophia Lee",
            "Dylan Ross",
            "Emma Watson",
            "",
            "Special Effects Makeup:",
            "Harrison Wells",
            "Zara Ahmed",
            "Lucas Chen",
            "",
            "Hair Department Head:",
            "Charlotte Wong",
            "",
            "Key Hair Stylists:",
            "Maya Patterson",
            "Nicolas Laurent",
            "Olivia Stone",
            "",
            "Visual Effects by STARLIGHT STUDIOS",
            "",
            "VFX Supervisors:",
            "Declan Hayes",
            "Marcus Renner",
            "Olivia Carter",
            "",
            "VFX Artists:",
            "Kai Chen",
            "Luna Park",
            "Sebastian Ross",
            "Mia Zhang",
            "Oliver Kim",
            "Zoe Chen",
            "Atlas Murphy",
            "Nova Williams",
            "",
            "Digital Effects:",
            "Quantum Digital",
            "",
            "Lead Technical Directors:",
            "Ray Chen",
            "Sarah Kim",
            "Marcus Wong",
            "",
            "Animation Supervisor:",
            "Diana Lee",
            "",
            "Lead Animators:",
            "Kevin O'Brien",
            "Luna Chen",
            "Paolo Romano",
            "Yuki Sato",
            "",
            "Compositing Supervisor:",
            "Nathan Parker",
            "",
            "Lead Compositors:",
            "Emma Chen",
            "Marcus Kim",
            "Zara Thompson",
            "",
            "Sound Department:",
            "",
            "Sound Designer:",
            "Alexandra Thompson",
            "",
            "Supervising Sound Editor:",
            "Richard Chen",
            "",
            "Sound Mixing Team:",
            "Liam Foley",
            "Amelia Grayson",
            "Sebastian Wang",
            "Maria Rodriguez",
            "",
            "Foley Artist:",
            "Hannah Murphy",
            "",
            "Music Composed by",
            "Christopher Chen",
            "",
            "Orchestra Conducted by",
            "Maestro James Wilson",
            "",
            "Music Recorded at",
            "Abbey Road Studios, London",
            "",
            "Music Mixing:",
            "Thomas Anderson",
            "Sarah Chen",
            "",
            "Music Editors:",
            "Robert Kim",
            "Elena Santos",
            "",
            "Location Managers:",
            "Marcus Thompson",
            "Laura Chen",
            "David Martinez",
            "",
            "Transportation Department:",
            "Daisy Moore",
            "Brooke Scott",
            "Ryan Chen",
            "Maria Santos",
            "Thomas Wong",
            "",
            "Catering Services:",
            "Divine Cuisine Co.",
            "",
            "Head Chef:",
            "Marco Pierre",
            "",
            "Craft Services:",
            "Sarah's Kitchen Crew",
            "",
            "Security Team Lead:",
            "Christopher Morales",
            "",
            "Security Personnel:",
            "Jasmine Bell",
            "Kyle Adams",
            "Marcus Chen",
            "Laura Thompson",
            "",
            "Production Assistants:",
            "Tommy Chen",
            "Rachel Kim",
            "David Park",
            "Elena Martinez",
            "Michael Wong",
            "Sarah Thompson",
            "Lucas Santos",
            "Nina Rodriguez",
            "",
            "Script Supervisors:",
            "Emma Lawrence",
            "Marcus Chen",
            "",
            "Production Accountants:",
            "Sarah Matthews",
            "Thomas Chen",
            "",
            "Legal Team:",
            "Sterling & Associates",
            "",
            "Legal Counsel:",
            "Elizabeth Grayson",
            "Ian Taylor",
            "Marcus Wong",
            "",
            "Insurance Services:",
            "Global Film Insurance Co.",
            "",
            "Product Placement:",
            "Sarah Chen",
            "Marcus Thompson",
            "",
            "Marketing Team:",
            "Nova Marketing Group",
            "",
            "Publicity:",
            "Starlight PR",
            "",
            "EPK Team:",
            "Documentary Film Crew",
            "",
            "Behind the Scenes Photography:",
            "Raymond Chen",
            "",
            "Animal Wranglers:",
            "Hunter Foster",
            "Gemma Ross",
            "Sarah Thompson",
            "",
            "Dialogue Coach:",
            "Victoria Chen",
            "",
            "Language Consultants:",
            "Dr. Maria Rodriguez",
            "Prof. Chen Wei",
            "",
            "Historical Advisors:",
            "Dr. James Thompson",
            "Prof. Sarah Chen",
            "",
            "Scientific Consultants:",
            "Dr. Marcus Wong",
            "Dr. Elena Santos",
            "",
            "Medical Advisors:",
            "Dr. Sarah Thompson",
            "Dr. Chen Liu",
            "",
            "Special Thanks To:",
            "The City of Vancouver",
            "British Columbia Film Commission",
            "The Vancouver Police Department",
            "Vancouver General Hospital",
            "The University of British Columbia",
            "Stanley Park Conservation Society",
            "The Vancouver Public Library",
            "The Vancouver Botanical Gardens",
            "The Historical Society of British Columbia",
            "",
            "Extra Special Thanks:",
            "All our incredible background actors",
            "The wonderful people of Vancouver",
            "Our amazing production interns",
            "The supportive families of our crew",
            "Coffee shops that kept us going",
            "",
            "Very Special Thanks:",
            "Aidan Gallagher",
            "Brianna Morris",
            "Cameron Smith",
            "Dylan Harper",
            "Evelyn Ross",
            "Felix Carter",
            "Grace Turner",
            "Harrison Black",
            "Isabella King",
            "Jackie Summers",
            "Katherine Lee",
            "Landon Brooks",
            "Madeline White",
            "Nathaniel Carter",
            "Olivia Reyes",
            "Preston Hall",
            "Quinn Wallace",
            "Riley Scott",
            "Sophia Bennett",
            "Tanner Cooper",
            "Uma Patel",
            "Victoria Knight",
            "Wyatt Hughes",
            "Xavier Green",
            "Yasmine Brown",
            "Zachary Collins",
            "",
            "Filmed on Location in:",
            "Vancouver, British Columbia, Canada",
            "Victoria, British Columbia, Canada",
            "Whistler, British Columbia, Canada",
            "",
            "Shot on",
            "ARRI ALEXA LF",
            "",
            "Color Grading by",
            "Technicolor Creative Studios",
            "",
            "DI Colorist:",
            "Marcus Chen",
            "",
            "Post Production Sound Services by",
            "Skywalker Sound",
            "",
            "Digital Intermediate by",
            "Company 3",
            "",
            "Visual Effects and Animation by",
            "Industrial Light & Magic",
            "Weta Digital",
            "Framestore",
            "DNEG",
            "",
            "This film was made possible by the generous support of",
            "The Canadian Film Fund",
            "British Columbia Film Incentives",
            "The Vancouver Film Foundation",
            "",
            "No animals were harmed during the making of this film.",
            "",
            "©2024 Midnight Garden Productions Ltd.",
            "All Rights Reserved.",
            "",
            "Dedicated to all those who believe in storytelling.",
            "",
            "Thank you for watching.",
            "",
            "End of Production.",
            "",
        ]
        
    @staticmethod
    def _get_terminal_size() -> Tuple[int, int]:
        """Get the current terminal width and height."""
        try:
            size = shutil.get_terminal_size()
            return size.columns, size.lines
        except Exception:
            return 80, 24  # Default terminal size
            
    def _clear_screen(self):
        """Clear the terminal screen in a cross-platform way."""
        if platform.system() == 'Windows':
            os.system('cls')
        else:
            os.system('clear')
            
    def _center_text(self, text: str) -> str:
        """Center text for the current terminal width."""
        return text.center(self.terminal_width).rstrip()
        
    def scroll(self):
        """Run the credits scroll animation."""
        # Add padding at top and bottom for smooth scroll
        padding_lines = self.terminal_height
        padded_credits = [""] * padding_lines + self.credits + [""] * padding_lines
        
        try:
            for i in range(len(padded_credits) - self.terminal_height + 1):
                self._clear_screen()
                
                # Display current frame of credits
                visible_credits = padded_credits[i:i + self.terminal_height]
                for line in visible_credits:
                    print(self._center_text(line))
                    
                time.sleep(self.scroll_speed)
                
        except KeyboardInterrupt:
            self._clear_screen()
            print("\nCredits scroll interrupted.")
            
def main():
    scroller = CreditsScroller()
    scroller.scroll()
    
if __name__ == "__main__":
    main()
